# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - appformovies-api

on:
  push:
    branches:
#      - ElenaNavarro-CI-CD    
      - development
#    paths:
#      - 'src/AppForMovies.API**'      
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout
    env:
      API: ./src/AppForSEII2526.API/AppForSEII2526.API.csproj
      UT:  ./test/AppForSEII2526.UT/AppForSEII2526.UT.csproj


    steps:
      - name: Check out repository code branch development
        uses: actions/checkout@v4
        with:
            ref: 'development'

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies        
        run: |  
          dotnet restore ${{ env.API }} 
          dotnet restore ${{ env.UT }} 
      - name: Build with dotnet
        run: |
          dotnet build ${{ env.API }}  --configuration Release --no-restore
          dotnet build ${{ env.UT }}  --configuration Release --no-restore
      - name: Run unit tests with report
        run: dotnet test ${{ env.UT }} --configuration Release --no-build --logger "trx;LogFileName=TestResults.trx"

      - name: dotnet publish
        run: dotnet publish ${{ env.API }}  -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B3B5DE78DC8C4C63B0F7EFF5BF7249AB }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C67DD58674C8427F9B12BCCAD9960162 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5355A73F264345458A1BFB4A2495AE12 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'appformovies-api'
          slot-name: 'Production'
          package: .

          

